### ISSUE TITLE
[NuclearCraft] Одноблочные машины и инструменты

### ISSUE THREAD

**Issue by Donny-zs** [slitesun/Litecraft#8]
НК добавляет ряд ручных инструментов из своих материалов и одноблочные машины, их нужно убрать

**Comment by slitesun** [comment]
Я всё проверил, невозможно убрать только Decay Hastener всё остальное уберу

**Comment by slitesun** [comment]
https://github.com/slitesun/Litecraft/commit/9cd265c49530a5792d0cacb37841363a5627415c
